name: Reqnroll.Actions.Playwright

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/reqnroll.actions.playwright.yaml'
      - 'Plugins/Reqnroll.Actions.Playwright/**'
      - 'Plugins/Reqnroll.Actions.Configuration/**'
      - 'Plugins/*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/reqnroll.actions.playwright.yaml'
      - 'Plugins/Reqnroll.Actions.Playwright/**'
      - 'Plugins/Reqnroll.Actions.Configuration/**'
      - 'Plugins/*'
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    env:
        DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Authenticates packages to push to GPR
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' 
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build Plugins/Reqnroll.Actions.Playwright/Reqnroll.Actions.Playwright.sln

      - run: dotnet test Plugins/Reqnroll.Actions.Playwright/Reqnroll.Actions.Playwright.sln

      - name: Create the package
        run: dotnet pack --configuration Release Plugins/Reqnroll.Actions.Playwright/Reqnroll.Actions.Playwright.sln

      - name: Upload NuGet Package to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NuGet-Package
          path:  |
            Plugins/Reqnroll.Actions.Playwright/Reqnroll.Actions.Playwright/bin/Release/**/*.nupkg
            Plugins/Reqnroll.Actions.Configuration/Reqnroll.Actions.Configuration.Generation/bin/Release/**/*.nupkg
            

  release:
    runs-on: windows-latest
    env: 
      DOTNET_NOLOGO: true
    needs: build
    environment: NuGet.org
    if: github.ref == 'refs/heads/main'
    steps:
      # Authenticates packages to push to nuget.org.
      # It's only the way to push a package to nuget.org feed for macOS/Linux machines due to API key config store limitations.
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: NuGet-Package
          path: NuGet-Package
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Publish the package to nuget.org
        shell: pwsh
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.REQNROLL_ACTIONS_NUGET_TOKEN }}
        run: dotnet nuget push "**/*.nupkg" -k "$env:NUGET_AUTH_TOKEN" -s "https://api.nuget.org/v3/index.json" --skip-duplicate
        
